// ── PriceRadar Constants ──────────────────────────────────────────────────
// Shared across all PriceRadar sub-components. No logic, no imports.

export const CATEGORY_IDS = ['flights', 'hotels', 'camping', 'rentals'];

export const TRACKER_TYPES_BY_CAT = {
  flights: ['flight', 'google_flight'],
  hotels:  ['hotel'],
  camping: ['camping'],
  rentals: [],
};

// Shared Tailwind + inline-style constants for form inputs
export const inputCls   = 'w-full px-3 py-2 rounded-xl border text-sm focus:outline-none focus:ring-2 focus:ring-[var(--ws-accent)]';
export const inputStyle = 'background:var(--ws-surface2);border-color:var(--ws-border);color:var(--ws-text)';
export const labelCls   = 'block text-xs font-bold uppercase tracking-wider mb-1';

// Top airports with IATA + city name for local autocomplete filtering
export const AIRPORTS = [
  { iata: 'VIE', city: 'Wien', country: 'AT' },
  { iata: 'MUC', city: 'München', country: 'DE' },
  { iata: 'FRA', city: 'Frankfurt', country: 'DE' },
  { iata: 'BER', city: 'Berlin', country: 'DE' },
  { iata: 'HAM', city: 'Hamburg', country: 'DE' },
  { iata: 'STR', city: 'Stuttgart', country: 'DE' },
  { iata: 'DUS', city: 'Düsseldorf', country: 'DE' },
  { iata: 'CGN', city: 'Köln', country: 'DE' },
  { iata: 'NUE', city: 'Nürnberg', country: 'DE' },
  { iata: 'ZRH', city: 'Zürich', country: 'CH' },
  { iata: 'GVA', city: 'Genf', country: 'CH' },
  { iata: 'BSL', city: 'Basel', country: 'CH' },
  { iata: 'BGY', city: 'Bergamo / Mailand', country: 'IT' },
  { iata: 'MXP', city: 'Mailand Malpensa', country: 'IT' },
  { iata: 'FCO', city: 'Rom', country: 'IT' },
  { iata: 'VCE', city: 'Venedig', country: 'IT' },
  { iata: 'NAP', city: 'Neapel', country: 'IT' },
  { iata: 'BLQ', city: 'Bologna', country: 'IT' },
  { iata: 'PMO', city: 'Palermo', country: 'IT' },
  { iata: 'CAG', city: 'Cagliari', country: 'IT' },
  { iata: 'TRN', city: 'Turin', country: 'IT' },
  { iata: 'FLR', city: 'Florenz', country: 'IT' },
  { iata: 'LIN', city: 'Mailand Linate', country: 'IT' },
  { iata: 'LNZ', city: 'Linz', country: 'AT' },
  { iata: 'GRZ', city: 'Graz', country: 'AT' },
  { iata: 'SZG', city: 'Salzburg', country: 'AT' },
  { iata: 'INN', city: 'Innsbruck', country: 'AT' },
  { iata: 'LHR', city: 'London Heathrow', country: 'GB' },
  { iata: 'LGW', city: 'London Gatwick', country: 'GB' },
  { iata: 'STN', city: 'London Stansted', country: 'GB' },
  { iata: 'MAN', city: 'Manchester', country: 'GB' },
  { iata: 'DUB', city: 'Dublin', country: 'IE' },
  { iata: 'BCN', city: 'Barcelona', country: 'ES' },
  { iata: 'MAD', city: 'Madrid', country: 'ES' },
  { iata: 'PMI', city: 'Palma de Mallorca', country: 'ES' },
  { iata: 'ALC', city: 'Alicante', country: 'ES' },
  { iata: 'AGP', city: 'Málaga', country: 'ES' },
  { iata: 'CDG', city: 'Paris Charles de Gaulle', country: 'FR' },
  { iata: 'ORY', city: 'Paris Orly', country: 'FR' },
  { iata: 'NCE', city: 'Nizza', country: 'FR' },
  { iata: 'MRS', city: 'Marseille', country: 'FR' },
  { iata: 'AMS', city: 'Amsterdam', country: 'NL' },
  { iata: 'BRU', city: 'Brüssel', country: 'BE' },
  { iata: 'CPH', city: 'Kopenhagen', country: 'DK' },
  { iata: 'OSL', city: 'Oslo', country: 'NO' },
  { iata: 'ARN', city: 'Stockholm', country: 'SE' },
  { iata: 'HEL', city: 'Helsinki', country: 'FI' },
  { iata: 'ATH', city: 'Athen', country: 'GR' },
  { iata: 'SKG', city: 'Thessaloniki', country: 'GR' },
  { iata: 'HER', city: 'Heraklion (Kreta)', country: 'GR' },
  { iata: 'CFU', city: 'Korfu', country: 'GR' },
  { iata: 'RHO', city: 'Rhodos', country: 'GR' },
  { iata: 'IST', city: 'Istanbul', country: 'TR' },
  { iata: 'SAW', city: 'Istanbul Sabiha', country: 'TR' },
  { iata: 'AYT', city: 'Antalya', country: 'TR' },
  { iata: 'OPO', city: 'Porto', country: 'PT' },
  { iata: 'LIS', city: 'Lissabon', country: 'PT' },
  { iata: 'FAO', city: 'Faro (Algarve)', country: 'PT' },
  { iata: 'PRG', city: 'Prag', country: 'CZ' },
  { iata: 'BUD', city: 'Budapest', country: 'HU' },
  { iata: 'WAW', city: 'Warschau', country: 'PL' },
  { iata: 'KRK', city: 'Krakau', country: 'PL' },
  { iata: 'OTP', city: 'Bukarest', country: 'RO' },
  { iata: 'SOF', city: 'Sofia', country: 'BG' },
  { iata: 'ZAG', city: 'Zagreb', country: 'HR' },
  { iata: 'SPU', city: 'Split', country: 'HR' },
  { iata: 'DBV', city: 'Dubrovnik', country: 'HR' },
  { iata: 'TIA', city: 'Tirana', country: 'AL' },
  { iata: 'KIV', city: 'Chisinau', country: 'MD' },
  { iata: 'JFK', city: 'New York JFK', country: 'US' },
  { iata: 'EWR', city: 'New York Newark', country: 'US' },
  { iata: 'LAX', city: 'Los Angeles', country: 'US' },
  { iata: 'ORD', city: 'Chicago', country: 'US' },
  { iata: 'MIA', city: 'Miami', country: 'US' },
  { iata: 'DXB', city: 'Dubai', country: 'AE' },
  { iata: 'DOH', city: 'Doha', country: 'QA' },
  { iata: 'BKK', city: 'Bangkok', country: 'TH' },
  { iata: 'SIN', city: 'Singapur', country: 'SG' },
  { iata: 'HKG', city: 'Hongkong', country: 'HK' },
  { iata: 'NRT', city: 'Tokio Narita', country: 'JP' },
  { iata: 'KIX', city: 'Osaka', country: 'JP' },
  { iata: 'SYD', city: 'Sydney', country: 'AU' },
  { iata: 'MEL', city: 'Melbourne', country: 'AU' },
  { iata: 'GRU', city: 'São Paulo', country: 'BR' },
  { iata: 'EZE', city: 'Buenos Aires', country: 'AR' },
  { iata: 'CMN', city: 'Casablanca', country: 'MA' },
  { iata: 'TUN', city: 'Tunis', country: 'TN' },
  { iata: 'CAI', city: 'Kairo', country: 'EG' },
  { iata: 'HRG', city: 'Hurghada', country: 'EG' },
  { iata: 'SSH', city: 'Sharm el-Sheikh', country: 'EG' },
];

// Simple destination strings for hotels/camping autocomplete
export const DESTINATIONS = [
  'Wien', 'München', 'Berlin', 'Hamburg', 'Frankfurt', 'Stuttgart', 'Köln', 'Düsseldorf',
  'Zürich', 'Genf', 'Basel', 'Bern',
  'Mailand', 'Rom', 'Venedig', 'Florenz', 'Neapel', 'Bologna', 'Turin', 'Palermo', 'Sardegna',
  'Paris', 'Nizza', 'Marseille', 'Lyon', 'Bordeaux', 'Strasbourg',
  'Barcelona', 'Madrid', 'Palma de Mallorca', 'Valencia', 'Sevilla', 'Málaga', 'Ibiza',
  'London', 'Manchester', 'Edinburgh', 'Dublin',
  'Amsterdam', 'Brüssel', 'Kopenhagen', 'Stockholm', 'Oslo', 'Helsinki',
  'Prag', 'Budapest', 'Warschau', 'Krakau', 'Bukarest', 'Bratislava',
  'Athen', 'Thessaloniki', 'Santorini', 'Mykonos', 'Kreta', 'Rhodos', 'Korfu',
  'Istanbul', 'Antalya', 'Bodrum', 'Kappadokien',
  'Lissabon', 'Porto', 'Faro / Algarve', 'Madeira',
  'Dubrovnik', 'Split', 'Zadar', 'Zagreb', 'Boka Kotorska',
  "Côte d'Azur", 'Languedoc', 'Provence', 'Bretagne', 'Normandie',
  'Toskana', 'Venetien', 'Ligurien', 'Sizilien', 'Sardinien', 'Kalabrien', 'Apulien',
  'Katalonien', 'Costa Brava', 'Costa Blanca', 'Andalusien', 'Balearen',
  'Kroatien - Istrien', 'Kroatien - Dalmatien',
  'Schwarzwald', 'Bayern / Alpen', 'Österreich / Tirol', 'Schweiz Wallis',
  'Dubai', 'Marrakesch', 'Hurghada', 'Sharm el-Sheikh', 'Tunesien', 'Zypern',
  'New York', 'Miami', 'Los Angeles', 'Bali', 'Thailand - Phuket', 'Singapur',
];
